services:
  - type: web
    name: inline-crm
    runtime: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rails db:prepare
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: WEB_CONCURRENCY
        value: "1"
